### ISSUE TITLE
Compose objects

### ISSUE THREAD

**Issue by celsogg** [bodinsamuel/altheia#314]
Having 2 schemas for validations of object A and B. A = {a,b} and B = {c,d}, it is possible to create a validation of an object C that is composed by properties of oject A and B? Like Joi [concat](https://hapi.dev/module/joi/api/?v=17.1.1#anyconcatschema)

**Comment by bodinsamuel** [comment]
Hey @celsogg 
thanks for your question :)
there is no built-in feature to concat object validation but it's easily doable manually, for example like this:

```js
const valA = () => { 
  return {
    foo: alt.string(),
  }
};
const valB =  = () => { 
  return {
    bar: alt.number(),
  }
};
const valC = alt({ ...valA(), ...valB() }).validate();
```

I could think of a better API for composability, like:
```js
alt({ foo: alt.string() })
  .merge({ bar: alt.number() })
  .validate();
```
